import { Metadata } from "next";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";
import { TheFooter } from "@/components/TheFooter";
import { Providers } from "@/components/Providers";
import { dir } from "i18next";
import TranslationsProvider from "../i18n/translationProvider";
import initTranslations from "../i18n/i18nServer";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const i18nNamespaces = ["widget.account"];

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  //todo - серверный хук для подгрузки переводов в провайдер
  const { resources } = await initTranslations(lang, i18nNamespaces);
  console.log("🚀 ~ resources:", resources);

  return (
    <html lang={lang} dir={dir(lang)}>
      <body>
        <TranslationsProvider
          resources={resources}
          namespaces={i18nNamespaces}
          locale={lang}
        >
          <Providers>
            <TheHeader />
            <main className="container">{children}</main>
            {/* <TheFooter lang={lang} /> */}
          </Providers>
        </TranslationsProvider>
      </body>
    </html>
  );
}
