import { Metadata } from "next";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";
import { TheFooter } from "@/components/TheFooter";
import { Providers } from "@/components/Providers";
import { dir } from "i18next";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

// const languages = ["en", "ru"];

// export async function generateStaticParams() {
//   return languages.map((lang) => ({ lang }));
// }

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body>
        <Providers>
          <TheHeader />
          <main className="container">{children}</main>
          <TheFooter lang={lang} />
        </Providers>
      </body>
    </html>
  );
}
